CREATE TABLE IF NOT EXISTS `originals` (
  `heroid` varchar(4) NOT NULL,
  `original` varchar(4) NOT NULL,
  `description` varchar(32) NOT NULL,
  PRIMARY KEY (`heroid`)
) 

--
-- Dataark for tabell `originals`
--

INSERT INTO `originals` (`heroid`, `original`, `description`) VALUES
('E002', 'orig', 'Lightning Revenant'),
('E004', 'orig', 'Bone Fletcher'),
('E005', 'orig', 'Moon Rider'),
('E00P', 'orig', 'Twin Head Dragon'),
('E015', 'U008', 'Lycanthrope'),
('E01A', 'orig', 'Witch Doctor'),
('E01B', 'orig', 'Spectre'),
('E01C', 'orig', 'Warlock'),
('E01Y', 'orig', 'Templar Assassin'),
('EC45', 'orig', 'Faceless Void'),
('EC57', 'orig', 'Venomancer'),
('EC77', 'orig', 'Netherdrake'),
('Edem', 'orig', 'Anti-Mage'),
('Eevi', 'orig', 'Soul Keeper'),
('Ekee', 'orig', 'Tormented Soul'),
('Emns', 'orig', 'Prophet'),
('Emoo', 'orig', 'Enchantress'),
('Ewar', 'orig', 'Phantom Assassin'),
('H000', 'orig', 'Centaur Warchief'),
('H001', 'orig', 'Rogue Knight'),
('H004', 'orig', 'Slayer'),
('H008', 'orig', 'Bristleback'),
('H00A', 'orig', 'Holy Knight'),
('H00D', 'orig', 'Beastmaster'),
('H00E', 'Hlgr', 'Dragon Knight'),
('H00G', 'Hlgr', 'Dragon Knight'),
('H00H', 'orig', 'Oblivion'),
('H00I', 'orig', 'Geomancer'),
('H00K', 'orig', 'Goblin Techies'),
('H00N', 'orig', 'Dark Seer'),
('H00Q', 'orig', 'Sacred Warrior'),
('H00R', 'orig', 'Undying'),
('H00S', 'orig', 'Storm Spirit'),
('H00T', 'orig', 'Clockwerk Goblin'),
('H00U', 'orig', 'Invoker'),
('H00V', 'orig', 'Gorgon'),
('H06S', 'orig', 'Admiral Proudmoore'),
('H07I', 'H00R', 'Undying'),
('Hamg', 'orig', 'Treant Protector'),
('Harf', 'orig', 'Omniknight'),
('Hblm', 'orig', 'Keeper of the Light'),
('HC49', 'orig', 'Naga Siren'),
('HC92', 'orig', 'Stealth Assassin'),
('Hjai', 'orig', 'Crystal Maiden'),
('Hlgr', 'orig', 'Dragon Knight'),
('Hmbr', 'orig', 'Lord of Olympia'),
('Hmkg', 'orig', 'Ogre Magi'),
('Huth', 'orig', 'Ursa Warrior'),
('Hvsh', 'orig', 'Bloodseeker'),
('Hvwd', 'orig', 'Vengeful Spirit'),
('N00B', 'orig', 'Faerie Dragon'),
('N00R', 'orig', 'Pit Lord'),
('N014', 'N01O', 'Lone Druid'),
('N015', 'N01O', 'Lone Druid'),
('N016', 'orig', 'Troll Warlord'),
('N01A', 'orig', 'Silencer'),
('N01I', 'orig', 'Alchemist'),
('N01J', 'N01I', 'Alchemist'),
('N01O', 'orig', 'Lone Druid'),
('N01V', 'orig', 'Priestess of the Moon'),
('N01W', 'orig', 'Shadow Priest'),
('N02B', 'N016', 'Troll Warlord'),
('N0EG', 'orig', 'Windrunner'),
('Naka', 'orig', 'Bounty Hunter'),
('Nbbc', 'orig', 'Juggernaut'),
('Nbrn', 'orig', 'Drow Ranger'),
('NC00', 'orig', 'Skeleton King'),
('Nfir', 'orig', 'Shadow Fiend'),
('Npbm', 'orig', 'Pandaren Brewmaster'),
('Ntin', 'orig', 'Tinker'),
('O00J', 'orig', 'Spiritbreaker'),
('O00P', 'orig', 'Morphling'),
('Ofar', 'orig', 'Tidehunter'),
('Ogrh', 'orig', 'Phantom Lancer'),
('Opgh', 'orig', 'Axe'),
('Orkn', 'orig', 'Shadow Shaman'),
('Oshd', 'orig', 'Bane Elemental'),
('Otch', 'orig', 'Earthshaker'),
('tes2', 'orig', 'test2beskrivelse'),
('test', 'orig', 'testbeskrivelse'),
('U000', 'orig', 'Nerubian Assassin'),
('U006', 'orig', 'Broodmother'),
('U008', 'orig', 'Lycanthrope'),
('U00A', 'orig', 'Chaos Knight'),
('U00C', 'orig', 'Lifestealer'),
('U00E', 'orig', 'Necrolyte'),
('U00F', 'orig', 'Butcher'),
('U00K', 'orig', 'Sand King'),
('U00P', 'orig', 'Obsidian Destroyer'),
('Ubal', 'orig', 'Nerubian Weaver'),
('UC01', 'orig', 'Queen of Pain'),
('UC11', 'orig', 'Magnataur'),
('UC18', 'orig', 'Demon Witch'),
('UC42', 'orig', 'Doom Bringer'),
('UC60', 'orig', 'Necro''lic'),
('UC76', 'orig', 'Death Prophet'),
('UC91', 'orig', 'Slithereen Guard'),
('Ucrl', 'orig', 'Stone Giant'),
('Udea', 'orig', 'Lord of Avernus'),
('Udre', 'orig', 'Night Stalker'),
('Uktl', 'orig', 'Enigma'),
('Ulic', 'orig', 'Lich'),
('Usyl', 'orig', 'Dwarven Sniper');


CREATE TABLE IF NOT EXISTS scores (
	id INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , 
	category VARCHAR, 
	name VARCHAR, 
	server VARCHAR, 
	score DOUBLE
);